config/routes.rb
BundledUi::Engine.routes.draw do
  get "/open" => "explorer#open", as: :open
  root "explorer#index"
end

app/controllers/bundled_ui/application_controller.rb
module BundledUi
  class ApplicationController < ActionController::Base
  end
end

app/controllers/bundled_ui/explorer_controller.rb
require_dependency "bundled_ui/application_controller"

module BundledUi
  class ExplorerController < ApplicationController
    def index
      @specs = Bundler.definition.specs.to_a
    end

    def open
      spec = Bundler.definition.specs[params[:gem]].first
      if spec
        system( "subl #{spec.gem_dir}/ || sublime #{spec.gem_dir}/")
      end

      redirect_to :root
    end
  end
end

app/helpers/bundled_ui/application_helper.rb
module BundledUi
  module ApplicationHelper
  end
end

app/helpers/bundled_ui/explorer_helper.rb
module BundledUi
  module ExplorerHelper
  end
end

app/views/bundled_ui/explorer/index.html.erb
<table class="table table-striped table-bordered">
  <tr>
    <th>Gem</th>
    <th>Summary</th>
    <th>Dependancies</th>
  </tr>

  <% @specs.each do |spec| %>
    <tr>
      <td>
        <%= link_to "#{spec.name} #{spec.version}", spec.homepage %><br/>
        <img src="https://badge.fury.io/rb/<%= spec.name %>.svg"/>
      </td>
      <td><%= link_to spec.summary, open_path( :gem => spec.name ), "data-title": spec.description, "data-toggle": "tooltip", "data-placement": "bottom" %></td>
      <td>
        <% if spec.dependencies.size > 0 %>
          <div class="dropdown">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
              Dependencies
              <span class="caret"></span>
            </button>

            <ul class="dropdown-menu dropdown-menu-right" role="menu">
              <% spec.dependencies.each do |dep| 
                spec = Bundler.definition.specs[dep.name].first
                %>
                <li class="<%= spec.nil? ? 'disabled' : '' %>">
                  <% if spec %>
                    <%= link_to "#{dep.name} (#{dep.type}) #{dep.requirements_list.join( ", ")}", spec.homepage, "data-title": spec.description, "data-toggle": "tooltip", "data-placement": " auto" %>
                  <% else %>
                    <%= link_to dep.name, "#" %>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>
<script>
$( function() {
  $('[data-toggle="tooltip"]').tooltip();  
});
</script>

app/views/layouts/bundled_ui/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BundledUi</title>
  <script src="//code.jquery.com/jquery-2.1.4.min.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet"/>

  <%= stylesheet_link_tag    "bundled_ui/application", media: "all" %>
  <%= javascript_include_tag "bundled_ui/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>